import Link from "next/link";
import { readFile } from "fs/promises";
import { Shell } from "@/components/Shell";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";

async function readMarkdown(path: string) {
  try {
    return await readFile(path, "utf8");
  } catch {
    return "File not found.";
  }
}

export default async function SubmissionPage() {
  await requireUser();

  const report = await prisma.importReport.findFirst({
    orderBy: { id: "desc" },
  });

  const anomalyCount = report
    ? await prisma.anomaly.count({
        where: { reportId: report.id },
      })
    : 0;

  const readme = await readMarkdown("README.md");
  const scope = await readMarkdown("SCOPE.md");
  const decisions = await readMarkdown("DECISIONS.md");
  const aiUsage = await readMarkdown("AI_USAGE.md");

  return (
    <Shell title="Submission">
      <section id="summary" className="grid grid-4">
        <div className="stat">
          <div className="stat-label">Required docs</div>
          <div className="stat-value">4</div>
        </div>

        <div className="stat">
          <div className="stat-label">Import report</div>
          <div className="stat-value">{report ? "Ready" : "Pending"}</div>
        </div>

        <div className="stat">
          <div className="stat-label">Anomalies</div>
          <div className="stat-value">{anomalyCount}</div>
        </div>

        <div className="stat">
          <div className="stat-label">Database</div>
          <div className="stat-value">Relational</div>
        </div>
      </section>

      <section id="actions" className="card">
        <h2>Required deliverables</h2>

        <p className="subtle">
          This page collects the assignment deliverables in one place. The import
          report is generated by the app after importing the CSV.
        </p>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 10,
            marginTop: 12,
          }}
        >
          <a className="btn light" href="#readme">
            README
          </a>

          <a className="btn secondary" href="#scope">
            SCOPE
          </a>

          <a className="btn secondary" href="#decisions">
            DECISIONS
          </a>

          <a className="btn secondary" href="#ai-usage">
            AI_USAGE
          </a>

          <Link className="btn secondary" href="/import#details">
            Import Report
          </Link>

          <Link className="btn secondary" href="/expenses">
            Expense Trace
          </Link>

          <Link className="btn secondary" href="/groups">
            Groups
          </Link>
        </div>
      </section>

      <section id="visuals" className="grid grid-2">
        <div className="card">
          <h2>Import report status</h2>

          {report ? (
            <>
              <p className="subtle">
                Latest import file: <b>{report.filename}</b>
              </p>

              <p className="subtle">
                Rows seen: <b>{report.rowsSeen}</b>
              </p>

              <p className="subtle">
                Expenses imported: <b>{report.expensesImported}</b>
              </p>

              <p className="subtle">
                Settlements imported: <b>{report.settlementsImported}</b>
              </p>

              <p className="subtle">
                Rows skipped: <b>{report.rowsSkipped}</b>
              </p>

              <p className="subtle">
                Anomalies detected: <b>{anomalyCount}</b>
              </p>

              <Link className="btn light" href="/import#details">
                View Import Report
              </Link>
            </>
          ) : (
            <>
              <p className="subtle">
                No import report exists yet. Go to Import and click the bundled
                CSV import button.
              </p>

              <Link className="btn light" href="/import">
                Go to Import
              </Link>
            </>
          )}
        </div>

        <div className="card">
          <h2>Submission checklist</h2>

          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Requirement</th>
                  <th>Status</th>
                  <th>Where</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>Public deployed app URL</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>Render deployment URL</td>
                </tr>

                <tr>
                  <td>GitHub repository</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>GitHub repo</td>
                </tr>

                <tr>
                  <td>README.md</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>This page + repo root</td>
                </tr>

                <tr>
                  <td>SCOPE.md</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>Anomalies + schema</td>
                </tr>

                <tr>
                  <td>DECISIONS.md</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>Decision log</td>
                </tr>

                <tr>
                  <td>AI_USAGE.md</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>AI usage documentation</td>
                </tr>

                <tr>
                  <td>Import report</td>
                  <td>
                    <span className={report ? "badge ok" : "badge warn"}>
                      {report ? "Generated" : "Pending"}
                    </span>
                  </td>
                  <td>
                    <Link href="/import#details">Import page</Link>
                  </td>
                </tr>

                <tr>
                  <td>Relational DB</td>
                  <td>
                    <span className="badge ok">Done</span>
                  </td>
                  <td>prisma/schema.prisma</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section id="details" className="grid grid-2">
        <div className="card" id="readme">
          <h2>README.md</h2>
          <pre>{readme}</pre>
        </div>

        <div className="card" id="scope">
          <h2>SCOPE.md</h2>
          <pre>{scope}</pre>
        </div>

        <div className="card" id="decisions">
          <h2>DECISIONS.md</h2>
          <pre>{decisions}</pre>
        </div>

        <div className="card" id="ai-usage">
          <h2>AI_USAGE.md</h2>
          <pre>{aiUsage}</pre>
        </div>
      </section>
    </Shell>
  );
}
